services:
  postgres:
    image: postgres:16
    container_name: gosuslugi_pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gosuslugi
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d gosuslugi"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build: .
    container_name: gosuslugi_api
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"

volumes:
  pg_data:
